# Map tile configuration for SITL Canberra area
# Generated by download_map.py

MAP_TILE_PATH = "map_tile.png"

MAP_BOUNDS = (
    -35.406960932702006,  # min_lat
    -35.32633026307483,   # max_lat
    149.117431640625,     # min_lon
    149.21630859375       # max_lon
)

# Mission target for orbit mission (SITL default area center)
MISSION_TARGET = (-35.363261, 149.165230)