# Map tile configuration for SITL Canberra area
# Generated by download_map.py

MAP_TILE_PATH_OSM = "map_tile_osm.png"
MAP_TILE_PATH_TERRAIN = "map_tile_terrain.png"  # requires Stadia Maps API key
MAP_TILE_PATH = MAP_TILE_PATH_OSM  # default (terrain requires API key)

MAP_BOUNDS = (
    -35.38009299209215,   # min_lat
    -35.353216101238225,  # max_lat
    149.150390625,        # min_lon
    149.183349609375      # max_lon
)

# Mission target for orbit mission (SITL default area center)
MISSION_TARGET = (-35.357, 149.209)

# VLM input resolution — set per model (moondream: 256, VILA: 384, Gemma 4: 512)
VLM_IMAGE_SIZE = (512, 512)